services:
  backend-fusion-cache:
    container_name: backend-fusion-cache
    image: redis:6.0
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend-fusion-network

  backend-fusion-database:
    container_name: backend-fusion-database
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - backend-fusion-dbdata:/data/db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - backend-fusion-network

volumes:
  backend-fusion-dbdata:

networks:
  backend-fusion-network:
    driver: bridge