services:
  backend-fusion-cache:
    container_name: backend-fusion-cache
    image: redis:6.0
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend-fusion-network

  backend-fusion-database:
    container_name: backend-fusion-database
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - backend-fusion-dbdata:/data/db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - backend-fusion-network

  backend-fusion-api:
    build:
      dockerfile: Dockerfile
    container_name: backend-fusion-api
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - backend-fusion-database
      - backend-fusion-cache
    environment:
      ## SERVER CONFIG
      - PORT=8080
      - HOST=http://localhost
      ## DATABASE CONFIGURATION
      - DB_HOST=backend-fusion-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - SYNCHRONIZE=false
      # CONFIGURING CACHE
      - REDIS_HOST=backend-fusion-cache
      - REDIS_PORT=6379
    networks:
      - backend-fusion-network

volumes:
  backend-fusion-dbdata:

networks:
  backend-fusion-network:
    driver: bridge