name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Download Terraform Outputs Artifact
          run: |
            curl -o terraform-outputs.json ${{ vars.TERRAFORM_OUTUTS_JSON }}

        - name: Extract Values from JSON
          id: extract
          run: |
            # Use jq to extract the values from the JSON file
            db_host=$(jq -r '.db_host' terraform-outputs.json)

            # Set the extracted values as environment variables
            echo "DB_HOST=$db_host" >> $GITHUB_ENV

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ vars.DOCKER_PASSWORD }}
      
        - name: Set IMAGE_TAG
          id: set_tag
          run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

        - name: Build Docker image
          run: |
            docker build --build-arg PORT=${{ vars.PORT }} --build-arg HOST=${{ vars.HOST }} --build-arg DB_HOST=$DB_HOST --build-arg DB_PORT=${{ vars.DB_PORT }} --build-arg DB_USERNAME=${{ vars.DB_USERNAME }}  --build-arg DB_PASSWORD=${{ vars.DB_PASSWORD }} --build-arg DB_NAME=${{ vars.DB_NAME }} --build-arg SYNCHRONIZE=${{ vars.SYNCHRONIZE }} --build-arg REDIS_HOST=${{ vars.REDIS_HOST }} --build-arg REDIS_PORT=6379 -t "${{ vars.DOCKER_USERNAME }}/${{ vars.APPLICATION_NAME }}:$IMAGE_TAG" .

        - name: Push Docker image
          run: |
            docker push "${{ vars.DOCKER_USERNAME }}/${{ vars.APPLICATION_NAME }}:$IMAGE_TAG"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download Terraform Outputs Artifact
        run: |
          curl -o terraform-outputs.json ${{ vars.TERRAFORM_OUTUTS_JSON }}

      - name: Extract Values from JSON
        id: extract
        run: |
          # Use jq to extract the values from the JSON file
          ec2_hostname=$(jq -r '.ec2_hostname' terraform-outputs.json)
          ssh_private_key_url=$(jq -r '.ssh_private_key_url' terraform-outputs.json)

          # Set the extracted values as environment variables
          echo "EC2_HOSTNAME=$ec2_hostname" >> $GITHUB_ENV
          echo "SSH_PRIVATE_KEY_URL=$ssh_private_key_url" >> $GITHUB_ENV
    
      - name: Download SSH Key from S3
        run: |
          curl -o deployer.pem "$SSH_PRIVATE_KEY_URL"
      
      - name: Set permissions for the SSH key
        run: chmod 600 deployer.pem
    
      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Add EC2 Host to known_hosts
        run: |
          ssh-keyscan -H "$EC2_HOSTNAME" >> ~/.ssh/known_hosts
        
      - name: Set IMAGE_TAG
        id: set_tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "IMAGE_TAG=${{ github.event.release.tag }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV # Default value if not on main or develop
          fi

      - name: Deploy to EC2
        run: |
          ssh -i deployer.pem -o StrictHostKeyChecking=no -t "ec2-user@$EC2_HOSTNAME" << 'EOF'
            sudo yum update -y
            echo "${{ vars.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin
          
            docker stop $(docker ps -q)
            docker rm $(docker ps -aq)

            # Run Redis container
            echo "Starting Redis container..."
            docker run -d --name ${{ vars.REDIS_CONTAINER_NAME }} -p 6379:6379 redis:6.0

            # Pull the application image
            echo "Pulling application image"
            docker pull "${{ vars.DOCKER_USERNAME }}/${{ vars.APPLICATION_NAME }}:$IMAGE_TAG"

          # Run the application container
            echo "Running application container"
            docker run -p 8080:8080 -d --name ${{ vars.APPLICATION_NAME }} "${{ vars.DOCKER_USERNAME }}/${{ vars.APPLICATION_NAME }}:${{ env.IMAGE_TAG }}"
          EOF